import type { Metadata } from "next";
import { NavBar } from "@/components/layout/navigation-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        {children}
        <NavBar />
      </body>
    </html>
  );
}
